# Generated by Django 6.0.3 on 2026-03-26 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_en',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('duration', models.IntegerField(help_text='Длительность в секундах')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music/tracks/')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.artist')),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
        ),
    ]
